// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7Sqr-XC6KdQyTYZdYApAS5BGUlll_BGs',
    appId: '1:8818680761:web:9c35e2267db3d9aacd8c68',
    messagingSenderId: '8818680761',
    projectId: 'fir-resellify',
    authDomain: 'fir-resellify.firebaseapp.com',
    storageBucket: 'fir-resellify.appspot.com',
    measurementId: 'G-GXHE6382XZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6OQ6hGGn5FpY2RwrjrxPsJOc3Gj96NKc',
    appId: '1:8818680761:android:5ffb02a64613fc87cd8c68',
    messagingSenderId: '8818680761',
    projectId: 'fir-resellify',
    storageBucket: 'fir-resellify.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3Y_yLUIV45_5bGqz1-DX2hwn0fmDboo0',
    appId: '1:8818680761:ios:4067b70d484852e2cd8c68',
    messagingSenderId: '8818680761',
    projectId: 'fir-resellify',
    storageBucket: 'fir-resellify.appspot.com',
    iosClientId:
        '8818680761-uo9o3fkf6622vvcm44hruobd40cee480.apps.googleusercontent.com',
    iosBundleId: 'com.example.resellify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3Y_yLUIV45_5bGqz1-DX2hwn0fmDboo0',
    appId: '1:8818680761:ios:548b6b9042e2758ccd8c68',
    messagingSenderId: '8818680761',
    projectId: 'fir-resellify',
    storageBucket: 'fir-resellify.appspot.com',
    iosClientId:
        '8818680761-h0ehqatap5qtgabsqp1k00ovralju848.apps.googleusercontent.com',
    iosBundleId: 'com.example.resellify.RunnerTests',
  );
}
